# =============================================================================
# FILE: secrets.py (AUTOMATICALLY GENERATED BY generate_secrets.py)
# DO NOT EDIT THIS FILE MANUALLY. DO NOT COMMIT TO VERSION CONTROL.
# =============================================================================
# -*- coding: utf-8 -*-
from __future__ import annotations

class Secrets:
    """
    This class holds all secrets loaded from the .env file.
    It is generated automatically and should not be version controlled.
    """
    GEMINI_API_KEY: str = "AIzaSyAhMc3TMyn08T2Nmub7xa509Pthx_mpu6M"
    PERPLEXITY_API_URL: str = "https://api.perplexity.ai/v1/query"
    PERPLEXITY_API_KEY: str = "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"
    DEEPSEEK_API_URL: str = "https://api.deepseek.ai/v1/query"
    DEEPSEEK_API_KEY: str = "sk-37e1f2d1034048289975d28d9fedc7bb"
    OPENAI_API_KEY: str = "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"
    CRAWLER_HEADLESS: str = "true"
    CRAWLER_DEFAULT_WAIT_TIME: str = "25"
    CRAWLER_SITES_FILE: str = "config/crawler_sites.json"
    CRAWLER_PARALLEL_COLLECT: str = "false"
    CONFIG_STRICT_ENV: str = "false"
    FLASK_APP: str = "app:create_app"
    BUYANDSHIP_EMAIL: str = "fukukei4416@gmail.com"
    BUYANDSHIP_USERNAME: str = "fukukei"
    BUYANDSHIP_PASSWORD: str = "uLETUZfFQCJVV3W"
    PLAYWRIGHT_HEADFUL: str = "1"
    PLAYWRIGHT_SLOWMO: str = "300"