# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test11():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_11(self):
    self.driver.get("https://www.buyma.com/")
    self.driver.set_window_size(1215, 775)
    self.driver.find_element(By.ID, "js-pc-header-login-link").click()
    self.driver.execute_script("window.scrollTo(0,182)")
    self.driver.execute_script("window.scrollTo(0,280.6666564941406)")
    self.driver.find_element(By.ID, "txtLoginId").click()
    self.driver.find_element(By.ID, "txtLoginId").click()
    self.driver.find_element(By.ID, "txtLoginId").send_keys("y.n.441622@gmail.com")
    self.driver.find_element(By.ID, "Sale_Bg").click()
    self.driver.find_element(By.ID, "txtLoginPass").click()
    self.driver.find_element(By.ID, "txtLoginPass").send_keys("kenshin4416")
    self.driver.find_element(By.ID, "login_do").click()
    self.driver.find_element(By.CSS_SELECTOR, ".my-page-profile__btn .fab-icon-dashboard-exhibit").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".my-page-profile__btn .fab-icon-dashboard-exhibit")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.LINK_TEXT, "カタログから出品する").click()
    self.driver.find_element(By.CSS_SELECTOR, ".catalogs-table__row:nth-child(5) .catalogs-table__image-item:nth-child(1) > .catalogs-table__image").click()
    self.driver.find_element(By.LINK_TEXT, "利用特約に同意し、画像を保存する").click()
