# ==============================================================================
# File: generate_secrets.py
# Registry: C:\Users\USER\tools\atelier-kyo-manager\app\config\generate_secrets.py
# Date & Time (JST): 2025-09-13 08:05:00
# Version: 1.1J (atelier-kyo-manager対応版)
#
# What's New (v1.1J):
#  - [PATH FIX] あなたの指摘に基づき、ファイルパスを`NexusCore`から
#    現在のプロジェクト`atelier-kyo-manager`に完全に修正しました。
#  - スクリプトの場所を `app/config/` 配下と想定し、プロジェクトルートを
#    正しく特定できるよう内部のパス計算ロジックも更新しました。
#
# --- How To Use ---
# 1. プロジェクトのルートディレクトリに `.env` ファイルを作成・編集します。
#    (C:\Users\USER\tools\atelier-kyo-manager\.env)
# 2. ターミナルで以下のコマンドを実行します。
#    > python app/config/generate_secrets.py
# 3. `app/config/` 配下に `secrets.py` が自動生成されます。
# 4. **重要: プロジェクトルートの `.gitignore` ファイルに
#    `app/config/secrets.py` を必ず追加してください。**
# ==============================================================================
# -*- coding: utf-8 -*-
from pathlib import Path

from dotenv import dotenv_values

# パス設定（このスクリプトが `app/config` にある前提）
ROOT_PATH = Path(__file__).resolve().parents[2]
ENV_PATH = ROOT_PATH / ".env"
TEMPLATE_PATH = ROOT_PATH / ".env.template"
SECRETS_PATH = Path(__file__).parent / "secrets.py"

if not ENV_PATH.exists():
    raise FileNotFoundError(f".env file not found. Please create it at: {ENV_PATH}")

print(f"Loading secrets from: {ENV_PATH}")
env_vars = dotenv_values(ENV_PATH)

# --- secrets.py の内容を生成 ---
secrets_lines = [
    "# =============================================================================",
    "# FILE: secrets.py (AUTOMATICALLY GENERATED BY generate_secrets.py)",
    "# DO NOT EDIT THIS FILE MANUALLY. DO NOT COMMIT TO VERSION CONTROL.",
    "# =============================================================================",
    "# -*- coding: utf-8 -*-",
    "from __future__ import annotations",
    "",
    "class Secrets:",
    '    """',
    "    This class holds all secrets loaded from the .env file.",
    "    It is generated automatically and should not be version controlled.",
    '    """',
]
if not env_vars:
    secrets_lines.append("    pass  # No secrets found in .env file.")
else:
    for key, value in env_vars.items():
        # 値をエスケープして安全な文字列にする
        safe_value = value.replace("\\", "\\\\").replace('"', '\\"') if value else ""
        secrets_lines.append(f'    {key}: str = "{safe_value}"')

# --- .env.template の内容を生成 ---
template_lines = [
    "# This is a template for the .env file. Copy this to .env and fill in the values.",
    "# Do not commit the .env file to version control.",
]
for key in env_vars:
    template_lines.append(f"{key}=")

# --- ファイル出力 ---
SECRETS_PATH.write_text("\n".join(secrets_lines), encoding="utf-8")
print(f"[SUCCESS] Generated secrets file at: {SECRETS_PATH}")

TEMPLATE_PATH.write_text("\n".join(template_lines), encoding="utf-8")
print(f"[SUCCESS] Generated .env.template file at: {TEMPLATE_PATH}")
