# ----------------------------------------------------------------
#  ファイル名: ai_generate_descriptions.py
#  役割:
#    商品情報に基づき、最適なプロンプトを構築し、
#    AILlmControllerを通じて商品説明文を生成するエージェント。
# ----------------------------------------------------------------

from .ai_llm_controller import AILlmController
import logging

class DescriptionGenerator:
    """商品説明文の生成を専門に行うエージェントクラス。"""
    def __init__(self):
        self.controller = AILlmController()

    def generate(self, product_info: dict, model_name: str = 'gemini') -> str:
        """
        商品情報から説明文を生成する。
        使用するモデルを 'gemini' または 'deepseek' から選択できる。
        """
        logging.info(f"Generating description for product: {product_info.get('name', 'N/A')}")
        
        # あなたが作り上げた、高品質な出力を引き出すプロンプトを維持・活用します
        prompt = f"""
あなたはBUYMA専門のプロのコピーライターです。
以下の商品情報に基づき、顧客の購買意欲を掻き立てる、魅力的で分かりやすい商品説明文を作成してください。

# 商品情報
- ブランド: {product_info.get('brand', '未設定')}
- 商品名: {product_info.get('name', '未設定')}
- カテゴリ: {product_info.get('category', '未設定')}
- 特徴: {product_info.get('features', '特記事項なし')}

# 作成ルール
- 全体で200〜300文字程度にまとめてください。
- 最も重要なセールスポイントを冒頭に記述してください。
- 箇条書きを効果的に使用し、商品のスペックや魅力を視覚的に伝えてください。
- 読者の感情に訴えかけるような、丁寧で高級感のある文体を心がけてください。
- 友人におすすめするような、少しパーソナルなトーンも歓迎します。
- 「激安」「最安値」といった安易な表現は絶対に使用しないでください。
- 最後に、商品の魅力を要約するような、心を動かす一文を添えてください。
"""
        
        description = self.controller.generate(prompt, model_name=model_name)
        logging.info(f"Successfully generated description using {model_name}.")
        return description

    def batch_process(self, products_info: list[dict], model_name: str = 'gemini') -> list[str]:
        """複数の商品情報を一括で処理する。"""
        descriptions = []
        for i, info in enumerate(products_info, 1):
            print(f"Processing item {i}/{len(products_info)}: {info.get('name', 'N/A')}")
            desc = self.generate(info, model_name)
            descriptions.append(desc)
        return descriptions

# --- このファイルが直接実行された場合のテスト用コード ---
if __name__ == '__main__':
    # このテストを実行するには、Flaskアプリケーションのコンテキストが必要です。
    # 実際の使用時は、Flaskのルート（routes.pyなど）から呼び出してください。
    print("これは商品説明文生成モジュールです。")
    print("Flaskアプリケーションのルートから呼び出して使用してください。")
    
    # --- 使用方法のサンプル ---
    # from app.utils.ai_generate_descriptions import DescriptionGenerator
    #
    # generator = DescriptionGenerator()
    # product = {
    #     'brand': 'CHANEL',
    #     'name': 'クラシック ハンドバッグ',
    #     'category': 'バッグ・カバン > ショルダーバッグ・ポシェット',
    #     'features': 'ラムスキン, ゴールド金具, ダブルフラップ'
    # }
    #
    # # Geminiを使って生成
    # desc_gemini = generator.generate(product, model_name='gemini')
    # print("--- Generated by Gemini ---")
    # print(desc_gemini)
    #
    # # DeepSeekを使って生成
    # desc_deepseek = generator.generate(product, model_name='deepseek')
    # print("\n--- Generated by DeepSeek ---")
    # print(desc_deepseek)