"""add actual_purchase_jpy to brand_price

Revision ID: 446f3af8c029
Revises: ccbe9f7ed501
Create Date: 2026-06-06 23:23:33.545327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446f3af8c029'
down_revision = 'ccbe9f7ed501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand_price', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_purchase_jpy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('actual_purchase_source', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand_price', schema=None) as batch_op:
        batch_op.drop_column('actual_purchase_source')
        batch_op.drop_column('actual_purchase_jpy')

    # ### end Alembic commands ###
