"""init

Revision ID: a650d11a7549
Revises: 61ca5e71b2e4
Create Date: 2025-08-14 23:55:11.410372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a650d11a7549'
down_revision = '61ca5e71b2e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('listing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('platform', sa.VARCHAR(length=50), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('listing_date', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('platform_url', sa.VARCHAR(length=512), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('brand', sa.VARCHAR(length=128), nullable=True),
    sa.Column('purchase_price', sa.FLOAT(), nullable=False),
    sa.Column('selling_price', sa.FLOAT(), nullable=False),
    sa.Column('supplier_url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=512), nullable=True),
    sa.Column('stock_status', sa.BOOLEAN(), nullable=True),
    sa.Column('profit', sa.FLOAT(), nullable=True),
    sa.Column('transaction_fee', sa.FLOAT(), nullable=True),
    sa.Column('shipping_cost', sa.FLOAT(), nullable=True),
    sa.Column('customs_duty', sa.FLOAT(), nullable=True),
    sa.Column('procurement_fee', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
