"""Add chat_history table

Revision ID: chat_history_001
Revises: 61ca5e71b2e4
Create Date: 2025-01-15 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'chat_history_001'
down_revision = '61ca5e71b2e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_family', sa.String(length=50), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_history_session_id', 'chat_history', ['session_id'], unique=False)
    op.create_index('ix_chat_history_created_at', 'chat_history', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_history_created_at', table_name='chat_history')
    op.drop_index('ix_chat_history_session_id', table_name='chat_history')
    op.drop_table('chat_history')
    # ### end Alembic commands ###

