"""add_fr006_extension_fields_to_order

Revision ID: ccbe9f7ed501
Revises: fa15d94c15de
Create Date: 2026-04-17 15:45:10.329621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccbe9f7ed501'
down_revision = 'fa15d94c15de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extension_requested', sa.Boolean(), nullable=True, comment='延長申請済み'))
        batch_op.add_column(sa.Column('extension_reason', sa.Text(), nullable=True, comment='延長理由'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('extension_reason')
        batch_op.drop_column('extension_requested')

    # ### end Alembic commands ###
