"""add_fr005_pricing_fields

Revision ID: fa15d94c15de
Revises: 
Create Date: 2026-04-17 12:37:50.916093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa15d94c15de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_shipping_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('original_currency', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('item_category', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('item_category')
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('original_currency')
        batch_op.drop_column('warehouse_shipping_cost')

    # ### end Alembic commands ###
